//
//  ConversionModels.swift
//  DesafioBTG
//
//  Created by Robson Moreira on 18/02/20.
//  Copyright (c) 2020 Robson Moreira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Conversion {
    
    enum Quotes {
        
        struct Request: Codable {
            var currency: String
            var source: String
            var value: Double
            
            enum CodingKeys: String, CodingKey {
                case currency = "currencies"
                case source
                case value = ""
            }
        }
        
        struct Response: Codable {
            var quotes: [String: Double]
        }
        
        struct Quote {
            var fromTo: Double
        }
        
        struct ViewModel{
            var currentQuote: Double
        }
        
    }
    
}

extension Conversion.Quotes.Response {
    
    func mapFromQuote() -> Conversion.Quotes.Quote {
        return Conversion.Quotes.Quote(fromTo: self.quotes.first!.value)
    }
    
}
