//
//  CoinListingPresenter.swift
//  DesafioBTG
//
//  Created by Robson Moreira on 17/02/20.
//  Copyright (c) 2020 Robson Moreira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CoinListingPresenter: CoinListingPresentationDelegate {
    
    weak var viewController: CoinListingDisplayDelegate!
    
    func presentCurrencies(currencies: [CoinListing.Currencies.Currency]) {
        let viewModel = CoinListing.Currencies.ViewModel(currencies: currencies, currenciesFiltered: [])
        self.viewController.displayCurrencies(viewModel: viewModel)
    }
    
    func presentErrorInFetchCurrencies() {
        self.viewController.displayErrorInFetchCurrencies()
    }
    
    func presentSelectedSourceCurrency() {
        self.viewController.displaySourceCurrency()
    }
    
    func presentSelectedToCurrency() {
        self.viewController.displayToCurrency()
    }
    
    func presentCurrencySelected(currencySelected: CurrencySelected?) {
        self.viewController.setCurrencySelected(currencySelected: currencySelected)
    }
    
}
