//
//  CurrencyConversionWorkerProtocols.swift
//  CurrencyConverter
//
//  Created by Tiago Chaves on 09/02/20.
//  Copyright (c) 2020 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrencyConversionWorkerProtocol {
    func convert(_ value: Double, currency sourceDolarQuote: USDCurrencyQuote, to resultDolarQuote: USDCurrencyQuote) -> Double
}

protocol SupportedCurrenciesWorkerProtocol {
    func loadSupportedCurrencies(completion: @escaping (SupportedCurrencies?, Error?) -> ())
}

protocol ExchangeRatesWorkerProtocol {
    func getExchangeRates(completion: @escaping (ExchangeRates?, Error?) -> ())
}
