source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'Mobile Challenge' do
  use_frameworks!

  pod 'Alamofire', '~> 5.4'

  target 'Mobile ChallengeTests' do
    inherit! :search_paths

  end

  target 'Mobile ChallengeUITests' do

  end

end
