# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile-challenge-pedro-alvarez' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile-challenge-pedro-alvarez
	pod 'Alamofire', '~> 4.8.2'
	pod 'ObjectMapper', '~> 3.4.2'

  target 'mobile-challenge-pedro-alvarezTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobile-challenge-pedro-alvarezUITests' do
    # Pods for testing
  end

end
