//
//  ConversionInteractor.swift
//  DesafioBTG
//
//  Created by Robson Moreira on 18/02/20.
//  Copyright (c) 2020 Robson Moreira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ConversionInteractor: ConversionBusinessDelegate, ConversionDataStore {
    
    var presenter: ConversionPresentationDelegate!
    var worker: ConversionWorker!
    
    var sourceButtonText: String?
    var toButtonText: String?
    var currencySelected: CurrencySelected?
    
    init() {
        self.worker = ConversionWorker()
    }
    
    func setTextSourceButton() {
        self.presenter.presentSourceButton(sourceButtonText: self.sourceButtonText)
    }
    
    func setTextToButton() {
        self.presenter.presentToButton(toButtonText: self.toButtonText)
    }
    
    func convertCurrency(request: Conversion.Quotes.Request) {
        self.worker.fetchConvertedCurrency(request: request) { (response, error) in
            guard let response = response else {
                self.presenter.presentErrorInConvertCurrency()
                return
            }
            self.presenter.presentQuote(quote: response)
        }
    }
    
}
