//
//  SupportedCurrenciesInteractor.swift
//  CurrencyConverter
//
//  Created by Tiago Chaves on 12/02/20.
//  Copyright (c) 2020 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SupportedCurrenciesBusinessLogic {
    func loadSupportedCurrencies(request: SupportedCurrenciesVIPModels.LoadSupportedCurrencies.Request)
    func filterSupportedCurrencies(request: SupportedCurrenciesVIPModels.Filter.Request)
}

protocol SupportedCurrenciesDataStore {
    var supportedCurrencies: SupportedCurrencies? { get set }
}

class SupportedCurrenciesInteractor: SupportedCurrenciesBusinessLogic, SupportedCurrenciesDataStore {
    var presenter: SupportedCurrenciesPresentationLogic?
    var supportedCurrencies: SupportedCurrencies?
    
    // MARK: - Load supported currencies
    func loadSupportedCurrencies(request: SupportedCurrenciesVIPModels.LoadSupportedCurrencies.Request) {
        
    }
    
    //MARK: - Filter
    func filterSupportedCurrencies(request: SupportedCurrenciesVIPModels.Filter.Request) {
        
    }
}
