//
//  SupportedCurrenciesModels.swift
//  CurrencyConverter
//
//  Created by Tiago Chaves on 12/02/20.
//  Copyright (c) 2020 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SupportedCurrenciesVIPModels {
    // MARK: -
    enum LoadSupportedCurrencies {
        struct Request {
        }
        struct Response {
            let currencies: SupportedCurrencies
            let currencyType: CurrencyType
        }
        
        struct ViewModel {
            let currencies: [Currency]
            let currencyType: CurrencyType
        }
    }
    // MARK: -
    enum Filter {
        struct Request {
            let filter: String
        }
        struct Response {
            let currencies: [String: String]
        }
        
        struct ViewModel {
            let currencies: [Currency]
        }
    }
}
