//
//  SupportedCurrenciesRouter.swift
//  CurrencyConverter
//
//  Created by Tiago Chaves on 13/02/20.
//  Copyright (c) 2020 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SupportedCurrenciesRoutingLogic {
}

protocol SupportedCurrenciesDataPassing {
    var dataStore: SupportedCurrenciesDataStore? { get }
}

class SupportedCurrenciesRouter: NSObject, SupportedCurrenciesRoutingLogic, SupportedCurrenciesDataPassing {
    weak var viewController: SupportedCurrenciesViewController?
    var dataStore: SupportedCurrenciesDataStore?
}
