# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BTGChallenge' do
  inhibit_all_warnings!
  pod 'Moya', '~> 12.0'
  
  target 'BTGChallengeTests' do
    inherit! :search_paths
    pod 'Quick', '= 2.2.0'
     pod 'Nimble', '= 8.0.4'
    # Pods for testing
  end

end
