# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def defaultPods
  inhibit_all_warnings!
  pod 'Moya'
end

def testPods
  pod 'Quick'
  pod 'Nimble'
end

target 'BTGChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   defaultPods
  # Pods for BTGChallenge
end

target 'BTGChallengeTests' do
  inherit! :search_paths
  testPods
  # Pods for testing
end
