# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BtgChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BtgChallenge
  pod 'SwiftLint'
  pod 'SnapKit'

  target 'BtgChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BtgChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
