# Uncomment the next line to define a global platform for your project
 platform :ios, '13.5'

target 'Desafio BTG' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desafio BTG

  # REST
  pod 'Alamofire', '4.9.1'
  
  # JSON Parse
  pod 'SwiftyJSON'

end
