//
//  ExchangesRates.swift
//  CurrencyConverter
//
//  Created by Tiago Chaves on 09/02/20.
//  Copyright (c) 2020 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

struct ExchangesRates: Codable, CustomStringConvertible, Equatable {
    let success: Bool
    let source: String
    let timestamp: Double
    let quotes: [String: Double]
    
    var quotesDate: Date {
        return Date(timeIntervalSince1970: timestamp)
    }
    
    var description: String {
        return "Taxas de conversão de \(quotesDate) com base na moeda \(source)"
    }
}

extension ExchangesRates {
    func getUSDCurrencyQuotes() -> [USDCurrencyQuote] {
        let source = self.source
        var usdCurrencyQuotes: [USDCurrencyQuote] = []
        
        for (key, value) in self.quotes {
            let index = key.index(key.startIndex, offsetBy: source.count)
            let currencyInitials = key[index...]
            
            usdCurrencyQuotes.append(USDCurrencyQuote(currencyInitials: String(currencyInitials), quote: value))
        }
        
        return usdCurrencyQuotes
    }
}
