//
//  SupportedCurrencies.swift
//  CurrencyConverter
//
//  Created by Tiago Chaves on 09/02/20.
//  Copyright (c) 2020 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

struct SupportedCurrencies: Codable, CustomStringConvertible, Equatable {
    let success: Bool
    let currencies: [String: String]
    
    var description: String {
        return "\(currencies.count) moedas disponíveis para conversão."
    }
    
    init(success: Bool, currencies: [String: String]) {
        self.success = success
        self.currencies = currencies
    }
    
    init(withCoreDataObj obj: CoreDataSupportedCurrencies) {
        guard let currencies = obj.currencies as? [String: String] else {
            self.init(success: false, currencies: [:])
            return
        }
        
        self.init(success: true, currencies: currencies)
    }
}
