//
//  CurrencyConversionRouter.swift
//  CurrencyConverter
//
//  Created by Tiago Chaves on 13/02/20.
//  Copyright (c) 2020 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CurrencyConversionRoutingLogic {
    func routeToSupportedCurrencies(segue: UIStoryboardSegue?)
}

protocol CurrencyConversionDataPassing {
    var dataStore: CurrencyConversionDataStore? { get }
}

class CurrencyConversionRouter: NSObject, CurrencyConversionRoutingLogic, CurrencyConversionDataPassing {
    weak var viewController: CurrencyConversionViewController?
    var dataStore: CurrencyConversionDataStore?
    
    // MARK: Routing
    func routeToSupportedCurrencies(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! SupportedCurrenciesViewController
            destinationVC.delegate = viewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSupportedCurrencies(source: dataStore!, destination: &destinationDS)
        }
    }
    
    // MARK: Passing data
    func passDataToSupportedCurrencies(source: CurrencyConversionDataStore, destination: inout SupportedCurrenciesDataStore) {
        destination.supportedCurrencies = source.supportedCurrencies
        destination.currencyType = source.currencyType
    }
}
