//
//  CurrencyConversionInteractor.swift
//  CurrencyConverter
//
//  Created by Tiago Chaves on 09/02/20.
//  Copyright (c) 2020 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrencyConversionBusinessLogic {
    func getSupportedCurrencies()
}

protocol CurrencyConversionDataStore {
    //var name: String { get set }
}

class CurrencyConversionInteractor: CurrencyConversionBusinessLogic, CurrencyConversionDataStore {
    var presenter: CurrencyConversionPresentationLogic?
    var supportedCurrenciesWorker: SupportedCurrenciesWorkerProtocol
    //var name: String = ""
    
    init(supportedCurrenciesWorker: SupportedCurrenciesWorkerProtocol = NetworkSupportedCurrenciesWorker(dataManager: NetworkDataManager())) {
        self.supportedCurrenciesWorker = supportedCurrenciesWorker
    }
    
    // MARK: - Get Supported Currencies
    func getSupportedCurrencies() {
        supportedCurrenciesWorker.loadSupportedCurrencies { (currencies, error) in
            let response = CurrencyConversion.LoadSupportedCurrencies.Response(currencies: currencies, error: error)
            self.presenter?.formatCurrencyListForView(response: response)
        }
    }
}
