//
//  CurrencyCodes.swift
//  TrocaMoeda
//
//  Created by mac on 23/06/20.
//  Copyright © 2020 Saulo Freire. All rights reserved.
//

import Foundation

struct CurrencyCodes {
    let AED: String
    let AFN: String
    let ALL: String
    let AMD: String
    let ANG: String
    let AOA: String
    let ARS: String
    let AUD: String
    let AWG: String
    let AZN: String
    let BAM: String
    let BBD: String
    let BDT: String
    let BGN: String
    let BHD: String
    let BIF: String
    let BMD: String
    let BND: String
    let BOB: String
    let BRL: String
    let BTC: String
    let BWP: String
    let BYN: String
    let BYR: String
    let BZD: String
    let CAD: String
    let CDF: String
    let CHF: String
    let CLF: String
    let CLP: String
    let CNY: String
    let COP: String
    let CRC: String
    let CUC: String
    let CUP: String
    let CVE: String
    let CZK: String
    let DJF: String
    let DKK: String
    let DOP: String
    let DZD: String
    let EGP: String
    let ERN: String
    let ETB: String
    let EUR: String
    let FKP: String
    let GBP: String
    let GEL: String
    let GGP: String
    let GHS: String
    let GIP: String
    let GMD: String
    let GNF: String
    let GTQ: String
    let GYD: String
    let HKD: String
    let HNL: String
    let HRK: String
    let HTG: String
    let HUF: String
    let IDR: String
    let ILS: String
    let IMP: String
    let INR: String
    let IQD: String
    let IRR: String
    let ISK: String
    let JEP: String
    let JMD: String
    let JOD: String
    let JPY: String
    let KES: String
    let KGS: String
    let KHR: String
    let KMF: String
    let KPW: String
    let KRW: String
    let KWD: String
    let KYD: String
    let KZT: String
    let LAK: String
    let LBP: String
    let LKR: String
    let LRD: String
    let LSL: String
    let LTL: String
    let LVL: String
    let LYD: String
    let MAD: String
    let MDL: String
    let MGA: String
    let MKD: String
    let MMK: String
    let MNT: String
    let MOP: String
    let MRO: String
    let MUR: String
    let MVR: String
    let MWK: String
    let MXN: String
    let MYR: String
    let MZN: String
    let NAD: String
    let NGN: String
    let NIO: String
    let NOK: String
    let NPR: String
    let NZD: String
    let OMR: String
    let PAB: String
    let PEN: String
    let PGK: String
    let PHP: String
    let PKR: String
    let PLN: String
    let PYG: String
    let QAR: String
    let RON: String
    let RSD: String
    let RUB: String
    let RWF: String
    let SAR: String
    let SBD: String
    let SCR: String
    let SDG: String
    let SEK: String
    let SGD: String
    let SHP: String
    let SLL: String
    let SOS: String
    let SRD: String
    let STD: String
    let SVC: String
    let SYP: String
    let SZL: String
    let THB: String
    let TJS: String
    let TMT: String
    let TND: String
    let TOP: String
    let TRY: String
    let TTD: String
    let TWD: String
    let TZS: String
    let UAH: String
    let UGX: String
    let USD: String
    let UYU: String
    let UZS: String
    let VEF: String
    let VND: String
    let VUV: String
    let WST: String
    let XAF: String
    let XAG: String
    let XAU: String
    let XCD: String
    let XDR: String
    let XOF: String
    let XPF: String
    let YER: String
    let ZAR: String
    let ZMK: String
    let ZMW: String
    let ZWL: String
}
