//
//  TranslatedCurrencies.swift
//  TrocaMoeda
//
//  Created by mac on 23/06/20.
//  Copyright © 2020 Saulo Freire. All rights reserved.
//

import Foundation

struct TranslatedCurrencies {
    static let shared = TranslatedCurrencies()
    let currencies = [
    "AED": "Dirham dos Emirados Árabes Unidos",
    "AFN": "Afegane Afeganistão",
    "ALL": "Lek Albanês",
    "AMD": "Dram Armênio",
    "ANG": "Florim das Antilhas Neerlandesas",
    "AOA": "Kwanza Angolano",
    "ARS": "Peso Argentino",
    "AUD": "Dólar Australiano",
    "AWG": "Florim Arubano",
    "AZN": "Manat Arzebaijano",
    "BAM": "Marco Convertível Bósnio",
    "BBD": "Dólar Barbadense",
    "BDT": "Taka (Bangladesh)",
    "BGN": "Lev Búlgaro",
    "BHD": "Dinar Bareinita",
    "BIF": "Franco do Burúndi",
    "BMD": "Dólar Bermudense",
    "BND": "Dólar do Brunei",
    "BOB": "Boliviano da Bolívia",
    "BRL": "Real",
    "BSD": "Dólar Bahamense",
    "BTC": "Bitcoin",
    "BTN": "Ngultrum Butanês",
    "BWP": "Pula Botsuanesa",
    "BYN": "Novo Rublo Bielorrusso",
    "BYR": "Rublo Bielorrusso",
    "BZD": "Dólar Belizenho",
    "CAD": "Dólar Canadense",
    "CDF": "Franco Congolês",
    "CHF": "Franco Suíço",
    "CLF": "Unidades de Fomento Chilenas",
    "CLP": "Peso Chileno",
    "CNY": "Remimbi (China)",
    "COP": "Peso Colombiano",
    "CRC": "Colón Costarriquenho",
    "CUC": "Peso Convertivel Cubano",
    "CUP": "Peso Cubano",
    "CVE": "Escudo Cabo-Verdiano",
    "CZK": "Coroa Tcheca",
    "DJF": "Franco do Djibouti",
    "DKK": "Coroa Dinamarquesa",
    "DOP": "Peso Dominicano",
    "DZD": "Dinar Argelino",
    "EGP": "Libra Egípcia",
    "ERN": "Nakfa (Eritreia)",
    "ETB": "Birr Etíope",
    "EUR": "Euro",
    "FJD": "Dólar Fijiano",
    "FKP": "Libra das Ilhas Malvinas",
    "GBP": "Libra esterlina",
    "GEL": "Lari Georgiano",
    "GGP": "Libra de Guernsey",
    "GHS": "Cedi Ganês",
    "GIP": "Libra de Gibraltar",
    "GMD": "Dalasi Gambiano",
    "GNF": "Franco Guineano",
    "GTQ": "Quetzal Guatemalteco",
    "GYD": "Dólar Guianense",
    "HKD": "Dólar de Hong Kong",
    "HNL": "Lempira Hondurenha",
    "HRK": "Kuna Croata",
    "HTG": "Gourde Haitiano",
    "HUF": "Florim Húngaro",
    "IDR": "Rupia Indonésia",
    "ILS": "Novo Shekel Israelense",
    "IMP": "Libra Manx",
    "INR": "Rupia Indiana",
    "IQD": "Dinar Iraquiano",
    "IRR": "Rial Iraniano",
    "ISK": "Coroa Islandesa",
    "JEP": "Libra de Jersey",
    "JMD": "Dólar Jamaicano",
    "JOD": "Dinar Jordaniano",
    "JPY": "Iene Japonês",
    "KES": "Xelim Queniano",
    "KGS": "Som Quirguiz",
    "KHR": "Riel (Camboja)",
    "KMF": "Franco Comoriano",
    "KPW": "Won Norte-Coreano",
    "KRW": "Won Sul-Coreano",
    "KWD": "Dinar Kuwaitiano",
    "KYD": "Dólar das Ilhas Cayman",
    "KZT": "Tenge Cazaque",
    "LAK": "Kip Laosiano",
    "LBP": "Libra Libanesa",
    "LKR": "Rupia do Sri Lanka",
    "LRD": "Dólar Liberiano",
    "LSL": "Loti (Lesotho)",
    "LTL": "Litas Lituano",
    "LVL": "Lats Letão",
    "LYD": "Dinar Líbio",
    "MAD": "Dirham Marroquino",
    "MDL": "Leu Moldávio",
    "MGA": "Ariary Malgaxe",
    "MKD": "Dinar Macedônio",
    "MMK": "Quiate (Mianmar)",
    "MNT": "Tugrik (Mongólia)",
    "MOP": "Pataca Macaense",
    "MRO": "Ouguiya Mauritana",
    "MUR": "Rupia Mauriciana",
    "MVR": "Rupia Maldívia",
    "MWK": "Kwacha Malauiana",
    "MXN": "Peso Mexicano",
    "MYR": "Ringgit Malaio",
    "MZN": "Metical Moçambicano",
    "NAD": "Dólar Namibiano",
    "NGN": "Naira Nigeriana",
    "NIO": "Córdoba Nicaraguense",
    "NOK": "Coroa Norueguesa",
    "NPR": "Rupia Nepalesa",
    "NZD": "Dólar Neozelandês",
    "OMR": "Rial Omanense",
    "PAB": "Balboa Panamenho",
    "PEN": "Novo Sol Peruano",
    "PGK": "Kina Papuásia",
    "PHP": "Peso Filipino",
    "PKR": "Rúpia Paquistanesa",
    "PLN": "Zloty Polonês",
    "PYG": "Guarani Paraguaio",
    "QAR": "Rial Catariano",
    "RON": "Leu Romeno",
    "RSD": "Dinar Sérvio",
    "RUB": "Rublo Russo",
    "RWF": "Franco Ruandês",
    "SAR": "Riyal Saudita",
    "SBD": "Dólar das Ilhas Salomão",
    "SCR": "Rupia das Seychelles",
    "SDG": "Libra Sudanesa",
    "SEK": "Coroa Sueca",
    "SGD": "Dólar Singapuriano",
    "SHP": "Libra de Santa Helena",
    "SLL": "Leone de Serra Leoa",
    "SOS": "Xelim Somali",
    "SRD": "Dólar Surinamês",
    "STD": "Dobra são-tomense",
    "SVC": "Colom salvadorenho",
    "SYP": "Libra Síria",
    "SZL": "Lilangeni Suazi",
    "THB": "Baht Tailandês",
    "TJS": "Somoni (Tajiquistão)",
    "TMT": "Manat turcomano",
    "TND": "Dinar tunisiano",
    "TOP": "Paʻanga tonganesa",
    "TRY": "Lira Turca",
    "TTD": "Dólar de Trinidad e Tobago",
    "TWD": "Novo dólar taiwanês",
    "TZS": "Xelim Tanzaniano",
    "UAH": "Hryvnia Ucraniano",
    "UGX": "Xelim Ugandês",
    "USD": "Dólar Americano",
    "UYU": "Peso Uruguaio",
    "UZS": "Som Uzbeque",
    "VEF": "Bolívar Venezuelano",
    "VND": "Dong Vietnamita",
    "VUV": "Vatu Vanuatu",
    "WST": "Tala (Samoa)",
    "XAF": "Franco CFA Central",
    "XAG": "Prata (troy ounce)",
    "XAU": "Ouro (troy ounce)",
    "XCD": "Dólar do Caribe Oriental",
    "XDR": "Direitos Especiais de Saque",
    "XOF": "Franco CFA Ocidental",
    "XPF": "Franco CFP",
    "YER": "Rial Iemenita",
    "ZAR": "Rand Sul-Africano",
    "ZMK": "Kwacha Zambiano (pre-2013)",
    "ZMW": "Kwacha Zambiano",
    "ZWL": "Dólar Zimbabueano"
    ]
}
