//
//  CurrencyLive.swift
//  MobileChallenge
//
//  Created by Thiago Lourin on 13/10/20.
//

import Foundation

struct CurrencyLive: APIResponse {
    let success: Bool
    let timestamp: CLong
    let source: String
    let quotes: CurrencyUSD
}

struct CurrencyUSD: APIResponse {
    let USDAED: Double
    let USDAFN: Double
    let USDALL: Double
    let USDAMD: Double
    let USDANG: Double
    let USDAOA: Double
    let USDARS: Double
    let USDAUD: Double
    let USDAWG: Double
    let USDAZN: Double
    let USDBAM: Double
    let USDBBD: Double
    let USDBDT: Double
    let USDBGN: Double
    let USDBHD: Double
    let USDBIF: Double
    let USDBMD: Double
    let USDBND: Double
    let USDBOB: Double
    let USDBRL: Double
    let USDBSD: Double
    let USDBTC: Double
    let USDBTN: Double
    let USDBWP: Double
    let USDBYN: Double
    let USDBYR: Double
    let USDBZD: Double
    let USDCAD: Double
    let USDCDF: Double
    let USDCHF: Double
    let USDCLF: Double
    let USDCLP: Double
    let USDCNY: Double
    let USDCOP: Double
    let USDCRC: Double
    let USDCUC: Double
    let USDCUP: Double
    let USDCVE: Double
    let USDCZK: Double
    let USDDJF: Double
    let USDDKK: Double
    let USDDOP: Double
    let USDDZD: Double
    let USDEGP: Double
    let USDERN: Double
    let USDETB: Double
    let USDEUR: Double
    let USDFJD: Double
    let USDFKP: Double
    let USDGBP: Double
    let USDGEL: Double
    let USDGGP: Double
    let USDGHS: Double
    let USDGIP: Double
    let USDGMD: Double
    let USDGNF: Double
    let USDGTQ: Double
    let USDGYD: Double
    let USDHKD: Double
    let USDHNL: Double
    let USDHRK: Double
    let USDHTG: Double
    let USDHUF: Double
    let USDIDR: Double
    let USDILS: Double
    let USDIMP: Double
    let USDINR: Double
    let USDIQD: Double
    let USDIRR: Double
    let USDISK: Double
    let USDJEP: Double
    let USDJMD: Double
    let USDJOD: Double
    let USDJPY: Double
    let USDKES: Double
    let USDKGS: Double
    let USDKHR: Double
    let USDKMF: Double
    let USDKPW: Double
    let USDKRW: Double
    let USDKWD: Double
    let USDKYD: Double
    let USDKZT: Double
    let USDLAK: Double
    let USDLBP: Double
    let USDLKR: Double
    let USDLRD: Double
    let USDLSL: Double
    let USDLTL: Double
    let USDLVL: Double
    let USDLYD: Double
    let USDMAD: Double
    let USDMDL: Double
    let USDMGA: Double
    let USDMKD: Double
    let USDMMK: Double
    let USDMNT: Double
    let USDMOP: Double
    let USDMRO: Double
    let USDMUR: Double
    let USDMVR: Double
    let USDMWK: Double
    let USDMXN: Double
    let USDMYR: Double
    let USDMZN: Double
    let USDNAD: Double
    let USDNGN: Double
    let USDNIO: Double
    let USDNOK: Double
    let USDNPR: Double
    let USDNZD: Double
    let USDOMR: Double
    let USDPAB: Double
    let USDPEN: Double
    let USDPGK: Double
    let USDPHP: Double
    let USDPKR: Double
    let USDPLN: Double
    let USDPYG: Double
    let USDQAR: Double
    let USDRON: Double
    let USDRSD: Double
    let USDRUB: Double
    let USDRWF: Double
    let USDSAR: Double
    let USDSBD: Double
    let USDSCR: Double
    let USDSDG: Double
    let USDSEK: Double
    let USDSGD: Double
    let USDSHP: Double
    let USDSLL: Double
    let USDSOS: Double
    let USDSRD: Double
    let USDSTD: Double
    let USDSVC: Double
    let USDSYP: Double
    let USDSZL: Double
    let USDTHB: Double
    let USDTJS: Double
    let USDTMT: Double
    let USDTND: Double
    let USDTOP: Double
    let USDTRY: Double
    let USDTTD: Double
    let USDTWD: Double
    let USDTZS: Double
    let USDUAH: Double
    let USDUGX: Double
    let USDUSD: Double
    let USDUYU: Double
    let USDUZS: Double
    let USDVEF: Double
    let USDVND: Double
    let USDVUV: Double
    let USDWST: Double
    let USDXAF: Double
    let USDXAG: Double
    let USDXAU: Double
    let USDXCD: Double
    let USDXDR: Double
    let USDXOF: Double
    let USDXPF: Double
    let USDYER: Double
    let USDZAR: Double
    let USDZMK: Double
    let USDZMW: Double
    let USDZWL: Double
}
