//
//  ConversionPresenter.swift
//  DesafioBTG
//
//  Created by Robson Moreira on 18/02/20.
//  Copyright (c) 2020 Robson Moreira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ConversionPresenter: ConversionPresentationDelegate {
    
    weak var viewController: ConversionDisplayDelegate!
    
    func presentSourceButton(sourceButtonText: String?) {
        self.viewController.displaySourceButton(sourceButtonText: sourceButtonText)
    }
    
    func presentToButton(toButtonText: String?) {
        self.viewController.displayToButton(toButtonText: toButtonText)
    }
    
    func presentQuote(quote: Conversion.Quotes.Quote) {
        let viewModel = Conversion.Quotes.ViewModel(currentQuote: quote.fromTo)
        self.viewController.displayCurrencies(viewModel: viewModel)
    }
    
    func presentErrorInConvertCurrency() {
        self.viewController.displayErrorInConvertCurrency()
    }
    
}
